accessible_charts: true
accessible_tabs: true
analytics:
  ua: ''
  gtag: ''
  gtm: ''
  ga_prod: ''
breadcrumbs:
  goal:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  indicator:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  post:
    - path: /
      label: general.home
    - path: /news
      label: menu.updates
contrast_type: default
cookie_consent_form:
  enabled: false
country:
  name: Australia
  adjective: Australian
create_goals:
  layout: goal-by-target-vertical
  previous_next_links: false
  goals: []
create_indicators:
  layout: indicator
  previous_next_links: false
create_pages:
  - filename: ''
    folder: /
    layout: frontpage-alt
    title: ''
  - filename: ''
    folder: /goals
    layout: goals
    title: ''
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: ''
  - filename: indicators.json
    folder: /
    layout: indicator-json
    title: ''
  - filename: ''
    folder: /search
    layout: search
    title: ''
custom_css: []
custom_js:
  - /assets/js/custom.js
data_edit_url: data
data_fields:
  units: ''
  series: ''
date_formats: []
disclaimer:
  phase: ''
  message: ''
email_contacts:
  questions: test@example.com
  suggestions: test@example.com
  functional: test@example.com
environment: staging
favicons: favicon.io
footer_language_toggle: none
footer_menu:
  - path: /contact-us
    translation_key: menu.contact_us
  - path: 'https://twitter.com/MyTwitterAccount'
    translation_key: general.twitter
  - path: 'https://facebook.com/MyFacebookAccount'
    translation_key: general.facebook
  - path: /about/cookies-and-privacy/
    translation_key: menu.cookies
frontpage_cards:
  - title: frontpage.download_all
    content: ''
    include: components/download-all-data.html
    button_label: ''
    button_link: ''
    rule_color: ''
  - title: Relevant websites and publications
    content: >
      [2030hub](https://the2030hub.com/)
      
      
      Together To Zero
      
      
      [St Helens Climate Change 
      Commission](https://www.sthelens.gov.uk/news/2021/march/24/climate-change-commission-to-support-greener-borough/#:~:text=At%20a%20full%20council%20meeting,is%20having%20on%20the%20borough.)
  - title: Useful resources
    content: >
      [About Local2030](https://www.local2030.org/about-us.php)


      [The Global Goals](https://www.globalgoals.org/)


      [Implementing the Sustainable Development
      Goals](https://www.gov.uk/government/publications/implementing-the-sustainable-development-goals/implementing-the-sustainable-development-goals--2)


      [UK data for Sustainable Development Goals](https://sdgdata.gov.uk/)
  - title: Affliated Data Platforms
    content: >- 
      [Liverpool SDG Data Platform](https://liverpool-sdg-data.github.io/)
frontpage_goals_grid:
  title: St Helens data for Sustainable Development Goal indicators 
  description: >-
    Click on each goal for our Sustainable Development Goal global indicator
    data.
frontpage_heading: ''
frontpage_instructions: ''
frontpage_introduction_banner:
   title: Welcome to St Helens SDG Data Platform.
   description: This is an open data platform for St Helens to help in achieving the
    Sustainable Development Goals (SDGs). This platform is constantly developing
    with the support of the local community in St Helens.
goal_image_base: 'https://open-sdg.org/sdg-translations/assets/img/goals'
goal_image_extension: ''
goals_page:
  title: general.goals
  description: goal.description
graph_color_headline: '#004466'
graph_color_headline_high_contrast: '#55a6e5'
graph_color_set: accessible
graph_color_list: []
graph_color_number: 0
graph_title_from_series: false
header:
  include: header-menu-left-aligned.html
header_language_toggle: dropdown
hide_empty_metadata: true
hide_single_series: true
hide_single_unit: true
indicator_config_form:
  enabled: true
  dropdowns: []
  repository_link: '/tree/develop/indicator-config'
  translation_link: ''
indicator_data_form:
  enabled: true
  repository_link: '/tree/develop/data'
indicator_metadata_form:
  enabled: true
  dropdowns: []
  repository_link: '/tree/develop/meta'
  translation_link: ''
  language: ''
  scopes:
    - national
    - global
  exclude_fields: []
  translated: false
languages:
  - en
  - es
languages_public: []
logos: []
map_layers: []
map_options:
  minZoom: 5
  maxZoom: 10
  tileURL: ''
  tileOptions:
    id: ''
    accessToken: ''
    attribution: ''
  colorRange: chroma.brewer.BuGn
  noValueColor: '#f0f0f0'
  styleNormal:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#888888'
    dashArray: ''
  styleHighlighted:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#111111'
    dashArray: ''
  styleStatic:
    weight: 2
    opacity: 1
    fillOpacity: 0
    color: '#172d44'
    dashArray: '5,5'
menu:
  - path: /goals
    translation_key: general.goals
    dropdown: []
  - path: /reporting-status
    translation_key: menu.reporting_status
    dropdown: []
  - path: /about
    translation_key: menu.about
    dropdown: []
  - path: /faq
    translation_key: menu.faq
    dropdown: []
  - path: /news
    translation_key: menu.updates
    dropdown: []
   - path: /jargon-buster
    translation_key: Jargon Buster
    dropdown: []  
metadata_edit_url: metadata
metadata_tabs: []
news:
  category_links: false
non_global_metadata: indicator.national_metadata
remote_data_prefix: 'https://open-sdg.org/open-sdg-data-starter'
reporting_status:
  title: status.reporting_status
  description: status.description
  disaggregation_tabs: false
repository_url_data: 'https://github.com/open-sdg/open-sdg-data-starter'
repository_url_site: ''
search_index_boost: []
search_index_extra_fields: []
series_toggle: true
sharethis_property: ''
site_config_form:
  enabled: true
  dropdowns: []
  repository_link: '/tree/develop/_data'
  translation_link: ''
validate_indicator_config: false
validate_site_config: false
x_axis_label: ''
